language: java
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer
script: 
  - "mvn clean install -Dci"
notifications:
  email:
    recipients:
      - spmallette@gmail.com
      - me@gremlin.guru
      - robdale@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
