language: java
notifications:
  email:
    - okrammarko@gmail.com
    - spmva@genoprime.com
    - josh@fortytwo.net
  hipchat:
      rooms:
        secure: "QPSIDcKeqElL85bbTQ7kG3DIX/MvwErMMB1o/Ri/7FL5grzeoBMOaRWtQX8MqW0+wsdnxPavILAYv+LRcTKragR6f69es+phCRgOybgXTV0/83tyLyx0FbdNnJGwyZcvGoxA2t8HO4Its5SNUXVDdDDMr+uNl9/Lxqm75yo5qqs="
jdk:
  - oraclejdk8
