language: java
notifications:
  email:
    - okrammarko@gmail.com
    - spmva@genoprime.com
    - josh@fortytwo.net
    - daniel@thinkaurelius.com
  hipchat:
    secure: "KL0XyQjycrXTUjXSXmvjDTs5fdcAi2Gl2PbuYMWslT8BjxduhVHBZ4OpHSUEkcFLS66blS2SMZNDYfXu3lHWWSxLSoPXubf+BvTOmvBm/wOTudxmKj17UnPUvSbH+KW08mOJBhsJ/0Sok6pcfmjSKLvlau8muttGQ7Yexd0pIOs="
jdk:
  - oraclejdk8

env:
  global:
    - secure: "BiSlH/eLH3R6lrUQeX6T1merzNCQtALmxr0iMlPCBeBakiBxwVEb2eyRx8HsYUBopeMKSuOjQmwd3x3U7/99ylHC9KbmmgtrTpdQErUHJeWr/XLE4YPbFPfU2dJMPkz0PZQLzM57ATei847ik7FMuCKPu/h2/Z7bAmLfjYRQA2Q="