host: localhost
port: 8182
threadPoolWorker: 16
threadPoolBoss: 1
graphs: {
  g: config/tinkergraph-empty.properties}
use:
  - [org.apache.commons, commons-math3, "3.2"]
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math, org.apache.commons.math3.util.FastMath],
    staticImports: [java.lang.Math.PI]}}
metrics: {
  consoleReporter: {interval: 180000}}
staticFilePath: src/main/resources/web