host: localhost
port: 8182
graphs: {
  g: config/tinkergraph-empty.properties}
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math],
    staticImports: [java.lang.Math.PI]}}
staticFilePath: src/main/resources/web