host: localhost
port: 8182
threadPoolWorker: 4
gremlinPool: 16
scriptEvaluationTimeout: 30000
serializedResponseTimeout: 30000
serializeResultTimeout: 200
graphs: {
  g: config/tinkergraph-empty.properties}
use:
  - [org.apache.commons, commons-math3, "3.2"]
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math, org.apache.commons.math3.util.FastMath],
    staticImports: [java.lang.Math.PI]}}
serializers:
  - { className: com.tinkerpop.gremlin.driver.ser.KryoMessageSerializerV1d0 }
  - { className: com.tinkerpop.gremlin.driver.ser.JsonMessageSerializerGremlinV1d0 }
metrics: {
  slf4jReporter: {enabled: true, interval: 180000}}
threadPoolBoss: 1
frameQueueSize: 256
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
